#ifndef Constants_h
#define Constants_h

#define RELAY_ON LOW
#define RELAY_OFF HIGH
#define STATE_ON 1
#define STATE_OFF 0
#define BUTTON_ACTIVE LOW

#define DEFAULT_PIR_DETECTOR_ACTIVE_TIME 10000
#define DEFAULT_PIR_DETECTOR_GRACE_PERIOD 5000
#define DEFAULT_DHT_UPDATE_TIME 30000

#endif